services:
  portal-postgres:
    image: "postgres:9.6-alpine"
    container_name: portal-postgres
    volumes:
      - portal-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal

volumes:
  portal-data:
